module BotClient
  class Application
    type event = apiGatewayV2HTTPEvent # ActiveFunction sig/aws_events

    def self.handler: (event: event, context: untyped) 
      -> ActiveFunction::Functions::Response::responseHash
  end
end
