# frozen_string_literal: true

source "https://rubygems.org" do
  gem 'activefunction'

  eval_gemfile "gemfiles/rubocop.gemfile"
  eval_gemfile "gemfiles/rbs.gemfile"
  eval_gemfile "gemfiles/minitest.gemfile"
  eval_gemfile "gemfiles/dev_server.gemfile"

  group :development, :test do
    gem 'pry-byebug', platform: :mri
    gem "ruby-next", "~> 0.15"
    gem "dotenv"
  end
end
