# frozen_string_literal: true

source "https://rubygems.org" do
  eval_gemfile "gemfiles/rubocop.gemfile"
  eval_gemfile "gemfiles/rbs.gemfile"
  eval_gemfile "gemfiles/minitest.gemfile"
  eval_gemfile "gemfiles/dev_server.gemfile"

  gem 'activefunction', "= 0.3.0", git: "https://github.com/DanilMaximov/activefunction.git"

  group :test, :development do
    gem 'pry-byebug', platform: :mri
    gem "rake", ">= 13.0"
    gem "rack", "= 3.0.0"
    gem "rackup"
    gem "ruby-next", "~> 0.14.0"
    gem "listen", "~> 3.8.0"
    gem "zeitwerk", "~> 2.6.0"
  end
end
