# frozen_string_literal: true

begin
  require "rake/testtask"

  Rake::TestTask.new do |t|
    t.libs << "test"
    t.libs << "src"
    t.test_files = FileList["test/**/*_test.rb"]
    t.warning    = false
    t.verbose    = true
  end
rescue LoadError
  task(:test) {}
end

begin
  require "rubocop/rake_task"

  RuboCop::RakeTask.new
rescue LoadError
  task(:rubocop) {}
end

begin
  task :steep do
    require "steep"
    require "steep/cli"

    Steep::CLI.new(argv: ["check"], stdout: $stdout, stderr: $stderr, stdin: $stdin).run
  end

  namespace :steep do
    task :stats do
      exec "bundle exec steep stats --log-level=fatal --format=table'"
    end
  end
rescue LoadError
  task(:steep) {}
end

desc "Run Ruby Next nextify"
task :nextify do
  sh "bundle exec ruby-next nextify -V"
end

desc "Lambda Package"
task :package do
  require "fileutils"

  FileUtils.rm_rf "vendor/*"
  FileUtils.cp_r "src", "vendor"
  FileUtils.cp_r "Gemfile", "vendor"
  FileUtils.cd "vendor" do
    sh "bundle exec ruby-next nextify ./src --single-version --edge --overwrite --transpile-mode=ast"
    sh " bundle install --path .bundle --without 'development test'"
  end
end

task default: %i[test rubocop steep]

